FROM ubuntu:16.04

# INSTALL RUBY

RUN apt-get update \
  && apt-get install -y autoconf file g++ gcc libc-dev make pkg-config re2c zlib1g-dev git --no-install-recommends

RUN mkdir -p /usr/local/etc; \
  { \
    echo 'install: --no-document'; \
    echo 'update: --no-document'; \
  } >> /usr/local/etc/gemrc

ENV RUBY_MAJOR 2.3
ENV RUBY_VERSION 2.3.1
ENV RUBY_DOWNLOAD_SHA256 b87c738cb2032bf4920fef8e3864dc5cf8eae9d89d8d523ce0236945c5797dcd
ENV RUBYGEMS_VERSION 2.6.8

# some of ruby's build scripts are written in ruby
# we purge this later to make sure our final image uses what we just built
RUN set -ex; \
  buildDeps='bison libgdbm-dev ruby curl libssl-dev  libxml2-dev'; \
  apt-get update; \
  apt-get install -y --no-install-recommends $buildDeps; \
  rm -rf /var/lib/apt/lists/*; \
  curl -fSL -o ruby.tar.gz "http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.gz"; \
  echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.gz" | sha256sum -c -; \
  mkdir -p /usr/src/ruby; \
  tar -xzf ruby.tar.gz -C /usr/src/ruby --strip-components=1; \
  rm ruby.tar.gz

RUN cd /usr/src/ruby; \
  { echo '#define ENABLE_PATH_CHECK 0'; echo; cat file.c; } > file.c.new; \
  mv file.c.new file.c; \
  autoconf; \
  ./configure --disable-install-doc; \
  make -j"$(nproc)"; \
  make install; \
  apt-get purge -y --auto-remove $buildDeps; \
  gem update --system $RUBYGEMS_VERSION

RUN cd ~; \
  rm -r /usr/src/ruby

ENV BUNDLER_VERSION 1.13.6

RUN gem install bundler --version "$BUNDLER_VERSION"

# install things globally, for great justice
# and don't create ".bundle" in all our apps
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_PATH "$GEM_HOME"
ENV BUNDLE_BIN "$GEM_HOME/bin"
ENV BUNDLE_SILENCE_ROOT_WARNING 1
ENV BUNDLE_APP_CONFIG "$GEM_HOME"
ENV PATH $BUNDLE_BIN:$PATH
RUN mkdir -p "$GEM_HOME" "$BUNDLE_BIN"; \
  chmod 777 "$GEM_HOME" "$BUNDLE_BIN"

#INSTALL NODEJS
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -; \
  apt-get update; \
  apt-get install -y nodejs --no-install-recommends

EXPOSE 3000
CMD [ "irb" ]
