FROM ubuntu:20.04

ENV PHP_INI_DIR /usr/local/etc/php
RUN mkdir -p $PHP_INI_DIR/conf.d

## Install last apache version ##
RUN apt update && apt upgrade \
  && DEBIAN_FRONTEND=noninteractive apt install -y dirmngr ca-certificates curl software-properties-common apt-transport-https \
  && add-apt-repository ppa:ondrej/apache2 -y

RUN apt-get update && apt-get install -y apache2 --no-install-recommends

RUN rm -rf /var/www/html \
  && mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html \
  && chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html

# Apache + PHP requires preforking Apache for best results
RUN a2dismod mpm_event && a2enmod mpm_prefork \
  && mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist \
  && rm /etc/apache2/conf-enabled/* /etc/apache2/sites-enabled/* \
  # Add SSL modules
  && mv /etc/apache2/mods-available/ssl* /etc/apache2/mods-enabled/ \
  && mv /etc/apache2/mods-available/socache* /etc/apache2/mods-enabled/ \
  && mv /etc/apache2/mods-available/rewrite* /etc/apache2/mods-enabled/ \
  && { \
  echo 'Mutex file:/var/lock/apache2 default'; \
  echo 'PidFile /var/run/apache2/apache2.pid'; \
  echo 'Timeout 300'; \
  echo 'KeepAlive On'; \
  echo 'MaxKeepAliveRequests 100'; \
  echo 'KeepAliveTimeout 5'; \
  echo 'User www-data'; \
  echo 'Group www-data'; \
  echo 'HostnameLookups Off'; \
  echo 'ErrorLog /proc/self/fd/2'; \
  echo 'LogLevel warn'; \
  echo ' '; \
  echo 'IncludeOptional mods-enabled/*.load'; \
  echo 'IncludeOptional mods-enabled/*.conf'; \
  echo ' '; \
  echo '# ports.conf'; \
  echo "Listen 80"; \
  echo ' '; \
  echo '<Directory />'; \
  echo '  Options FollowSymLinks'; \
  echo '  AllowOverride None'; \
  echo '  Require all denied'; \
  echo '</Directory>'; \
  echo ' '; \
  echo '<Directory /var/www/>'; \
  echo '  AllowOverride All'; \
  echo '  Require all granted'; \
  echo '</Directory>'; \
  echo ' '; \
  echo 'DocumentRoot /var/www/html'; \
  echo ' '; \
  echo 'AccessFileName .htaccess'; \
  echo '<FilesMatch "^\.ht">'; \
  echo '  Require all denied'; \
  echo '</FilesMatch>'; \
  echo ' '; \
  echo 'LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined'; \
  echo 'LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined'; \
  echo 'LogFormat "%h %l %u %t \"%r\" %>s %O" common'; \
  echo 'LogFormat "%{Referer}i -> %U" referer'; \
  echo 'LogFormat "%{User-agent}i" agent'; \
  echo ' '; \
  echo 'CustomLog /var/log/apache2/custom_log combined'; \
  echo ' '; \
  echo '<FilesMatch \.php$>'; \
  echo '  SetHandler application/x-httpd-php'; \
  echo '</FilesMatch>'; \
  echo ' '; \
  echo '# Multiple DirectoryIndex directives within the same context will add'; \
  echo '# to the list of resources to look for rather than replace'; \
  echo '# https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryindex'; \
  echo 'DirectoryIndex disabled'; \
  echo 'DirectoryIndex index.php index.html'; \
  echo ' '; \
  echo '# Disable TRACE http requests'; \
  echo 'TraceEnable off'; \
  echo ' '; \
  echo 'IncludeOptional conf-enabled/*.conf'; \
  echo 'IncludeOptional sites-enabled/*.conf'; \
  } > /etc/apache2/apache2.conf

ENV PHP_EXTRA_BUILD_DEPS apache2-dev
ENV PHP_EXTRA_CONFIGURE_ARGS --with-apxs2

ENV PHP_FILENAME php-7.4.33.tar.xz
ENV PHP_SHA256 924846abf93bc613815c55dd3f5809377813ac62a9ec4eb3778675b82a27b927

COPY php-ext-* /usr/local/bin/
RUN chmod 755 /usr/local/bin/php-ext-* \
  && apt-get update \
  && apt-get install -y autoconf file g++ gcc libc-dev make pkg-config re2c --no-install-recommends \
  # persistent / runtime deps
  && DEBIAN_FRONTEND=noninteractive apt-get install -y libedit2 libsqlite3-0 libxml2 --no-install-recommends

RUN set -xe; \
  buildDeps="$PHP_EXTRA_BUILD_DEPS libcurl4-openssl-dev libedit-dev libsqlite3-dev libssl-dev  libxml2-dev  xz-utils"; \
  apt-get update && apt-get install -y $buildDeps --no-install-recommends; \
  curl -fSL "https://www.php.net/distributions/$PHP_FILENAME" -o "$PHP_FILENAME"; \
  echo "$PHP_SHA256 *$PHP_FILENAME" | sha256sum -c -; \
  mkdir -p /usr/src/php; \
  tar -xf "$PHP_FILENAME" -C /usr/src/php --strip-components=1; \
  rm "$PHP_FILENAME"

# Install libraries required for PHP extensions
RUN apt-get update && apt-get install -y apt-utils git wget curl libxml2-dev libbz2-dev re2c libpng++-dev libjpeg-dev libvpx-dev zlib1g-dev \
  libgd-dev libssl-dev libtidy-dev libxslt1-dev libmagic-dev libexif-dev file libssh2-1-dev libaio-dev libbz2-dev libpng-dev \
  libpcre3-dev libfreetype6-dev libmcrypt-dev libxslt-dev xfonts-base xfonts-75dpi fonts-texgyre \
  fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei ttf-wqy-zenhei libzip-dev libonig-dev unzip openssl php-dev php-pear build-essential libaio1


RUN cd /usr/src/php; \
  ./configure \
    --with-config-file-path="$PHP_INI_DIR" \
    --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
    $PHP_EXTRA_CONFIGURE_ARGS \
    --disable-cgi \
    --enable-mysqlnd \
    --enable-mbstring \
    --enable-intl \
    --enable-pcntl \
    --with-mysqli \
    --with-curl \
    --with-libedit \
    --with-openssl \
    --with-zlib; \
  make -j"$(nproc)"; \
  make install; \
  { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; }; \
  make clean

# INSTALL AND CONFIGURE PHP EXTENSIONS
# Copy Oracle instantclient files (OS drivers)
COPY OracleClient/* /tmp/

RUN mkdir -p mkdir /usr/lib/oracle/21.9/client64 \
  && mv tmp/instantclient-basic-linux.x64-21.9.0.0.0dbru.zip /usr/lib/oracle/21.9/client64 \
  && mv tmp/instantclient-sdk-linux.x64-21.9.0.0.0dbru.zip /usr/lib/oracle/21.9/client64 \
  && cd /usr/lib/oracle/21.9/client64 \
  && unzip instantclient-basic-linux.x64-21.9.0.0.0dbru.zip \
  && unzip instantclient-sdk-linux.x64-21.9.0.0.0dbru.zip \
  && mv instantclient_21_9 lib \
  && cd /usr/lib/oracle/21.9/client64/lib/ \
  && echo /usr/lib/oracle/21.9/client64/lib > /etc/ld.so.conf.d/oracle.conf \
  && ldconfig

RUN pecl channel-update pecl.php.net && pecl install mcrypt-1.0.6 && php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
  && php-ext-configure oci8 --with-oci8=instantclient,/usr/lib/oracle/21.9/client64/lib \
  && php-ext-install iconv mbstring xsl soap bcmath bz2 calendar exif shmop gd zip oci8 \
  && php-ext-enable mcrypt opcache

# Install Redis PHP extension
RUN pecl install redis && php-ext-enable redis

# Install oauth (authentication) PHP extension
RUN pecl install oauth \
  && php-ext-enable oauth

# Needed for wkhtmltopdf, installed by composer
RUN apt-get install -y libxrender1

# Install base packages
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# Upgrade OpenSSL Version to 1.1.1t
RUN cp -R /usr/lib/ssl /usr/lib/ssl-1.1.1f \
  && wget https://www.openssl.org/source/openssl-1.1.1t.tar.gz \
  && tar -zxf openssl-1.1.1t.tar.gz \
  && rm openssl-1.1.1t.tar.gz \
  && cd openssl-1.1.1t \
  && ./config \
  && make \
  && make install \
  && mv /usr/bin/openssl /usr/bin/openssl-1.1.1f \
  && ln -s /usr/local/bin/openssl /usr/bin/openssl \
  && ldconfig \
  && cd /usr/local/ssl \
  && rmdir certs \
  && ln -s /etc/ssl/certs \
  && rmdir private \
  && ln -s /etc/ssl/private \
  && mv openssl.cnf openssl.cnf.original \
  && ln -s /etc/ssl/openssl.cnf

# Apache start command
COPY apache2-foreground /usr/local/bin/
RUN chmod 755 /usr/local/bin/apache2-foreground

EXPOSE 80
CMD ["apache2-foreground"]
